### PR TITLE
New short course slides: week 1

### PR DESCRIPTION
**Pull request by charlielafosse**
@sofer @yvonne-liu @bobbysebolao and @matthewdking would be good to get your eyes on this.

New accompanying markdown file with structure, notes etc. to follow too

### CODE REVIEW

**Comment by charlielafosse** [comment]
@sofer any feedback on this and also [this](https://github.com/foundersandcoders/fac-access/pull/9)? I can get cracking with week 2 once you're all happy 🤸‍♂

**Comment by bobbysebolao** [comment]
These new slides look amazing @charlielafosse! 🍾

**Comment by charlielafosse** [comment]
No worries. Do you know when the next short course is kicking off? @yvonne-liu  🌚

**Comment by sofer** [comment]
@charlielafosse I am very very happy :-)

**Pull request merged**
